# Generated by Django 3.0.5 on 2020-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradie',
            fields=[
                ('TradieId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Pass', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100, null=True)),
                ('Suburb', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=5)),
                ('Postcode', models.CharField(max_length=5)),
                ('Company', models.CharField(max_length=50, null=True)),
                ('ABN', models.CharField(max_length=15)),
                ('BSB', models.CharField(max_length=10)),
                ('AccountNo', models.CharField(max_length=10)),
                ('AccountName', models.CharField(max_length=30)),
                ('AccountStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
