# Generated by Django 3.0.5 on 2020-08-24 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
                ('needCertification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderStatus', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=15, null=True)),
                ('category', models.CharField(max_length=20)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('Tradie', 'Tradie'), ('Customer', 'Customer')], default='Customer', max_length=10, null=True)),
                ('user_hp', models.ImageField(default='default_hp.png', upload_to='user_hp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('myUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('SA', 'SA'), ('WA', 'WA'), ('NT', 'NT'), ('TAS', 'TAS')], default='ACT', max_length=10)),
                ('postcode', models.CharField(max_length=5)),
                ('cardHolder', models.CharField(max_length=30)),
                ('cardNo', models.CharField(max_length=30)),
                ('cardValidDate', models.CharField(max_length=5)),
                ('accountStatus', models.CharField(choices=[('Active', 'Active'), ('Banned', 'Banned')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tradie',
            fields=[
                ('myUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('SA', 'SA'), ('WA', 'WA'), ('NT', 'NT'), ('TAS', 'TAS')], default='ACT', max_length=10)),
                ('postcode', models.CharField(max_length=5)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('travelDistance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ABN', models.CharField(max_length=15)),
                ('BSB', models.CharField(max_length=10)),
                ('accountNo', models.CharField(max_length=10)),
                ('accountName', models.CharField(max_length=30)),
                ('accountStatus', models.CharField(choices=[('Active', 'Active'), ('Banned', 'Banned')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TradieJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.JobType')),
                ('tradie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Tradie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'order')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='tradie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Tradie'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateName', models.CharField(max_length=50)),
                ('certificateStatus', models.CharField(max_length=10)),
                ('expireDate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tradie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Tradie')),
            ],
            options={
                'unique_together': {('tradie', 'certificateName')},
            },
        ),
    ]
