# Generated by Django 3.0.5 on 2020-05-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=15, null=True),
        ),
    ]
