# Generated by Django 3.0.5 on 2020-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
