# Generated by Django 3.0.5 on 2020-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='price',
        ),
        migrations.AddField(
            model_name='tradiejobtype',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
