# Generated by Django 3.0.5 on 2020-04-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Pass', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100, null=True)),
                ('Suburb', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=5)),
                ('Postcode', models.CharField(max_length=5)),
                ('CardHolder', models.CharField(max_length=30)),
                ('CardNo', models.CharField(max_length=30)),
                ('CardValidDate', models.CharField(max_length=5)),
                ('AccountStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(max_length=15)),
                ('Category', models.CharField(max_length=20)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Customer')),
                ('TradieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Tradie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=10)),
                ('Review', models.CharField(max_length=255)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Order')),
            ],
            options={
                'unique_together': {('UserId', 'OrderId')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CertificateName', models.CharField(max_length=50)),
                ('CertificateStatus', models.CharField(max_length=10)),
                ('TradieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Tradie')),
            ],
            options={
                'unique_together': {('TradieId', 'CertificateName')},
            },
        ),
    ]
