# Generated by Django 3.1 on 2020-09-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_auto_20200824_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cardHolder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cardNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cardValidDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='ABN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='BSB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='accountName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='accountNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
