# Generated by Django 3.0.5 on 2020-05-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_auto_20200501_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradie',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
