# Generated by Django 3.0.5 on 2020-08-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_auto_20200824_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradie',
            name='ABN_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradie',
            name='BSB_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradie',
            name='accountName_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradie',
            name='accountNo_en',
            field=models.BooleanField(default=False),
        ),
    ]
