# Generated by Django 3.0.5 on 2020-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_auto_20200501_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_hp',
            field=models.ImageField(default='default_hp.png', upload_to='user_hp'),
        ),
    ]
