# Generated by Django 3.0.5 on 2020-08-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_auto_20200829_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradie',
            name='ABN_en',
        ),
        migrations.RemoveField(
            model_name='tradie',
            name='BSB_en',
        ),
        migrations.RemoveField(
            model_name='tradie',
            name='accountName_en',
        ),
        migrations.RemoveField(
            model_name='tradie',
            name='accountNo_en',
        ),
    ]
