# Generated by Django 3.0.5 on 2020-04-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0004_auto_20200415_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='ExpireDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='TravelDistance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
