# Generated by Django 3.0.5 on 2020-08-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0004_auto_20200829_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cardHolder',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cardNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cardValidDate',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='ABN',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='BSB',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='accountName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='accountNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
