# Generated by Django 3.0.5 on 2020-09-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0006_auto_20200829_0626'),
        ('Home_app', '0003_auto_20200901_0528'),
    ]

    operations = [
    ]
