# Generated by Django 3.0.5 on 2020-09-11 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0008_auto_20200903_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('AwaitingPayment', 'Awaiting Payment')], default='Unread', max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Customer')),
                ('tradie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.Tradie')),
            ],
        ),
    ]
