# Generated by Django 3.1 on 2020-09-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0009_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradie',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Responded', 'Responded'), ('Read', 'Read')], default='Unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradie',
            name='state',
            field=models.CharField(choices=[('ACT', 'ACT'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('SA', 'SA'), ('WA', 'WA'), ('NT', 'NT'), ('TAS', 'TAS')], default='ACT', max_length=10),
        ),
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image.png', upload_to='quotes_images')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_app.quote')),
            ],
        ),
    ]
