# Generated by Django 3.1 on 2020-09-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0010_auto_20200921_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Responded', 'Responded'), ('Declined', 'Declined'), ('Finished', 'Finished')], default='Unread', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteimage',
            name='image',
            field=models.ImageField(default='image.png', upload_to='quotes'),
        ),
    ]
