# Generated by Django 3.0.5 on 2020-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0011_auto_20200923_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='declineReason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='feedback',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
