# Generated by Django 3.0.5 on 2020-10-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0012_auto_20201001_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Responded', 'Responded'), ('TradieDeclined', 'Tradie Declined'), ('CustomerDeclined', 'Customer Declined'), ('Finished', 'Finished')], default='Unread', max_length=20),
        ),
    ]
