# Generated by Django 3.0.5 on 2020-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0013_auto_20201005_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
